# fly.toml app configuration file generated for empty-smoke-4793 on 2023-11-12T01:35:15-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "empty-smoke-4793"
primary_region = "lax"
console_command = "/code/manage.py shell"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
